### ISSUE TITLE
Can't connect to TVheadend

### ISSUE THREAD

**Issue by Bechrissed** [Helly1206/comskipper#1]
Hi, i'm having trouble using your script. I've modified the config xml but can't succesfully connect to TVheadend. I have tried multiple addresses, eg:

http://localhost
http://mydomain.com
http://localhost:9981
http://mydomain.com:9981
http://localhost:9981/

etc

Username and password are double checked and are correct. Any other options for debugging or a solution how to fix this?

**Comment by Bechrissed** [comment]
When I look at the python script you are appending :9981/status.xml so http://localhost should be working (hts_skipper runs ons same machine). 

One more detail is that when I look in the hts_skipper log the url doesn't seem correct:

 WARNING:Remaining connection attempts to http://domain.nl:

Notice the : in the end.... shouldn't this be http://domain.nl:9981/status.xml ??

Any other ideas?

**Comment by Helly1206** [comment]
Hi,


Can you enter  http://localhost<http://localhost/>::9981/status.xml in a browser? Preferably on the same system as you are running comskipper. Does it bring you to an xml page?


Helly.



________________________________
Van: Chris Koster <notifications@github.com>
Verzonden: donderdag 8 juni 2017 14:35
Aan: Helly1206/comskipper
CC: Subscribed
Onderwerp: Re: [Helly1206/comskipper] Can't connect to TVheadend (#1)


When I look at the python script you are appending :9981/status.xml so http://localhost should be working (hts_skipper runs ons same machine).

Any ideas?

**Comment by Bechrissed** [comment]
Yes, tried that yesterday. I do get the xml response

**Comment by Helly1206** [comment]
Which version of TVHeadend are you using? I didn't test with 4.2 yet. Maybe something has changed in the format, don't know. Do you get a particular error message? Can you send me the log file?


Thanks,

Helly.

________________________________
Van: Chris Koster <notifications@github.com>
Verzonden: vrijdag 9 juni 2017 08:50:53
Aan: Helly1206/comskipper
CC: Ivo Helwegen; Comment
Onderwerp: Re: [Helly1206/comskipper] Can't connect to TVheadend (#1)


Yes, tried that yesterday. I do get the xml response

**Comment by Bechrissed** [comment]
Im on vtheadend version 4.3-196~gad61cad

this is the log file:
2017-06-09 21:32:06,461 INFO:Comskip HTS Ready ...
2017-06-09 21:32:26,328 INFO:Comskip HTS Started ...
2017-06-09 21:32:26,387 WARNING:Remaining connection attempts to http://localhost: 2
2017-06-09 21:32:31,393 WARNING:Remaining connection attempts to http://localhost: 1
2017-06-09 21:32:36,399 WARNING:Remaining connection attempts to http://localhost: 0
2017-06-09 21:32:41,405 ERROR:Error establishing connection

my status.xml is the attachment.


[status.xml.zip](https://github.com/Helly1206/comskipper/files/1065074/status.xml.zip)

**Comment by Helly1206** [comment]
Hi,


xml still contains to same information, so that shouldn't be a problem. Just guessing, a few more questions:

  *   I'm pretty same thveadend is running on port 8891, as you are able to read the status.xml
  *   Is your authentication correct? You have to enter as userpass user:password in the hts_skipper.xml file. (I didn't test what happens with no password set).
  *   Are you sure tvheadend is running at the time you try to connect?
  *   Can you try running hts_skipper.py from the command-line? Then it should print the exception information when it is not able to connect to tvheadend. Then we can probable exactly see where this issue occurs.

Thanks,
Helly.

________________________________
Van: Chris Koster <notifications@github.com>
Verzonden: vrijdag 9 juni 2017 21:35:58
Aan: Helly1206/comskipper
CC: Ivo Helwegen; Comment
Onderwerp: Re: [Helly1206/comskipper] Can't connect to TVheadend (#1)

Im on vtheadend version 4.3-196~gad61cad

this is the log file:
2017-06-09 21:32:06,461 INFO:Comskip HTS Ready ...
2017-06-09 21:32:26,328 INFO:Comskip HTS Started ...
2017-06-09 21:32:26,387 WARNING:Remaining connection attempts to http://localhost: 2
2017-06-09 21:32:31,393 WARNING:Remaining connection attempts to http://localhost: 1
2017-06-09 21:32:36,399 WARNING:Remaining connection attempts to http://localhost: 0
2017-06-09 21:32:41,405 ERROR:Error establishing connection

my status.xml is the attachment.

--
kind regards,

Chris Koster


On 9 June 2017 at 19:04:57, Ivo Helwegen (notifications@github.com) wrote:

Which version of TVHeadend are you using? I didn't test with 4.2 yet. Maybe something has changed in the format, don't know. Do you get a particular error message? Can you send me the log file?


Thanks,

Helly.

________________________________
Van: Chris Koster <notifications@github.com>
Verzonden: vrijdag 9 juni 2017 08:50:53
Aan: Helly1206/comskipper
CC: Ivo Helwegen; Comment
Onderwerp: Re: [Helly1206/comskipper] Can't connect to TVheadend (#1)


Yes, tried that yesterday. I do get the xml response

**Comment by Bechrissed** [comment]
Yes i'm sure tvheadend is running, it's always running and I'm watching the tvh log simultaneously. I have entered the username and password (with syntax user:pass) and triple checked for typos.

I have have started hts_skipper.py from command line, it tells me a bit more. The script wasn't able to read/write the log file due to a lack of permissions. So I set the correct permissions. After that I try to run hts_skipper manually and get the following response:

HTTP Error 401: Unauthorized
HTTP Error 401: Unauthorized
HTTP Error 401: Unauthorized

**Comment by Bechrissed** [comment]
I think the authentication fails because you are using basic auth and my version of tvheadend requieres digest auth. I have tried to add digest auth myself, seems to start without errors now. I'm doing a test recording today and we'll see how that goes :)

**Comment by Bechrissed** [comment]
Ok problem solved, adding digest auth works. Recording was completed and everything is working now. I'll create a pull request later today for the fix.

**Comment by Helly1206** [comment]
Hi,


You're the best. Thanks a lot for helping debugging and solving this problem to make the tools even better.


Regards,

Helly.

________________________________
Van: Chris Koster <notifications@github.com>
Verzonden: zaterdag 10 juni 2017 11:56:05
Aan: Helly1206/comskipper
CC: Ivo Helwegen; Comment
Onderwerp: Re: [Helly1206/comskipper] Can't connect to TVheadend (#1)


Ok problem solved, adding digest auth works. Recording was completed and everything is working now. I'll create a pull request later today for the fix.

**Comment by KyleSanderson** [comment]
@Bechrissed any update on this?

**Comment by Bechrissed** [comment]
Unfortunately not, HTS skipper seems not working for me. I thought I fixed it and it did create some skipfiles in the beginning but now i'm seeing lot's of connection errors again. When connection is made I always get the following error and no skip file is generated:

    2017-09-04 01:47:26,129 INFO:DB: Recording - My tv recording started, but no file to skip found (yet)

I didn't really invest any more time in it. I think I was on the right track with the connection errors so fiddle around with that. Maybe you or the repo owner can fix it.

**Comment by KyleSanderson** [comment]
I appreciate the update @Bechrissed. The XML output parsing seems completely broken for me using TVHeadend which is still pinned on 4.0.9 on Gentoo; I started to update comskipper then gave up...

What are you using now if you don't mind me asking? I have my existing comskip (I've called it comscript for years; as a joke), but I'm looking to replace it with something a little more reasonable.

**Comment by Bechrissed** [comment]
To be honest i'm relying on my remote control skills to skip commercials :) So currently nothing automated for me. I'm still interested in automatic commercial skipping so i'll might try something else soon.

**Comment by Helly1206** [comment]
Hi,

I read your issues, but at the moment I don't have time to look into it. I need to do so, maybe later during winter.

Helly.

**Comment by Helly1206** [comment]
Hi,

The issue you are mentioning is solved now. It seems that the authentication type to access tvheadend needs to be changed from basic to digest for tvheadend 4.2 and higher. I was still running on 4.0 and didn't have any issues. 

Please update to version 1.0.2 and enjoy.

Helly.
